// Code generated by ent, DO NOT EDIT.

package order

import (
	"bot/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldID, id))
}

// MaintOrderNo applies equality check predicate on the "maintOrderNo" field. It's identical to MaintOrderNoEQ.
func MaintOrderNo(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldMaintOrderNo, v))
}

// VehiclePlateNo applies equality check predicate on the "vehiclePlateNo" field. It's identical to VehiclePlateNoEQ.
func VehiclePlateNo(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldVehiclePlateNo, v))
}

// VehicleTeamName applies equality check predicate on the "vehicleTeamName" field. It's identical to VehicleTeamNameEQ.
func VehicleTeamName(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldVehicleTeamName, v))
}

// MaintRequestType applies equality check predicate on the "maintRequestType" field. It's identical to MaintRequestTypeEQ.
func MaintRequestType(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldMaintRequestType, v))
}

// DispatchedStationId applies equality check predicate on the "dispatchedStationId" field. It's identical to DispatchedStationIdEQ.
func DispatchedStationId(v int) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldDispatchedStationId, v))
}

// StationName applies equality check predicate on the "stationName" field. It's identical to StationNameEQ.
func StationName(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldStationName, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldUpdatedAt, v))
}

// MaintOrderNoEQ applies the EQ predicate on the "maintOrderNo" field.
func MaintOrderNoEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldMaintOrderNo, v))
}

// MaintOrderNoNEQ applies the NEQ predicate on the "maintOrderNo" field.
func MaintOrderNoNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldMaintOrderNo, v))
}

// MaintOrderNoIn applies the In predicate on the "maintOrderNo" field.
func MaintOrderNoIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldMaintOrderNo, vs...))
}

// MaintOrderNoNotIn applies the NotIn predicate on the "maintOrderNo" field.
func MaintOrderNoNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldMaintOrderNo, vs...))
}

// MaintOrderNoGT applies the GT predicate on the "maintOrderNo" field.
func MaintOrderNoGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldMaintOrderNo, v))
}

// MaintOrderNoGTE applies the GTE predicate on the "maintOrderNo" field.
func MaintOrderNoGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldMaintOrderNo, v))
}

// MaintOrderNoLT applies the LT predicate on the "maintOrderNo" field.
func MaintOrderNoLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldMaintOrderNo, v))
}

// MaintOrderNoLTE applies the LTE predicate on the "maintOrderNo" field.
func MaintOrderNoLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldMaintOrderNo, v))
}

// MaintOrderNoContains applies the Contains predicate on the "maintOrderNo" field.
func MaintOrderNoContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldMaintOrderNo, v))
}

// MaintOrderNoHasPrefix applies the HasPrefix predicate on the "maintOrderNo" field.
func MaintOrderNoHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldMaintOrderNo, v))
}

// MaintOrderNoHasSuffix applies the HasSuffix predicate on the "maintOrderNo" field.
func MaintOrderNoHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldMaintOrderNo, v))
}

// MaintOrderNoEqualFold applies the EqualFold predicate on the "maintOrderNo" field.
func MaintOrderNoEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldMaintOrderNo, v))
}

// MaintOrderNoContainsFold applies the ContainsFold predicate on the "maintOrderNo" field.
func MaintOrderNoContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldMaintOrderNo, v))
}

// VehiclePlateNoEQ applies the EQ predicate on the "vehiclePlateNo" field.
func VehiclePlateNoEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldVehiclePlateNo, v))
}

// VehiclePlateNoNEQ applies the NEQ predicate on the "vehiclePlateNo" field.
func VehiclePlateNoNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldVehiclePlateNo, v))
}

// VehiclePlateNoIn applies the In predicate on the "vehiclePlateNo" field.
func VehiclePlateNoIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldVehiclePlateNo, vs...))
}

// VehiclePlateNoNotIn applies the NotIn predicate on the "vehiclePlateNo" field.
func VehiclePlateNoNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldVehiclePlateNo, vs...))
}

// VehiclePlateNoGT applies the GT predicate on the "vehiclePlateNo" field.
func VehiclePlateNoGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldVehiclePlateNo, v))
}

// VehiclePlateNoGTE applies the GTE predicate on the "vehiclePlateNo" field.
func VehiclePlateNoGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldVehiclePlateNo, v))
}

// VehiclePlateNoLT applies the LT predicate on the "vehiclePlateNo" field.
func VehiclePlateNoLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldVehiclePlateNo, v))
}

// VehiclePlateNoLTE applies the LTE predicate on the "vehiclePlateNo" field.
func VehiclePlateNoLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldVehiclePlateNo, v))
}

// VehiclePlateNoContains applies the Contains predicate on the "vehiclePlateNo" field.
func VehiclePlateNoContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldVehiclePlateNo, v))
}

// VehiclePlateNoHasPrefix applies the HasPrefix predicate on the "vehiclePlateNo" field.
func VehiclePlateNoHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldVehiclePlateNo, v))
}

// VehiclePlateNoHasSuffix applies the HasSuffix predicate on the "vehiclePlateNo" field.
func VehiclePlateNoHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldVehiclePlateNo, v))
}

// VehiclePlateNoEqualFold applies the EqualFold predicate on the "vehiclePlateNo" field.
func VehiclePlateNoEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldVehiclePlateNo, v))
}

// VehiclePlateNoContainsFold applies the ContainsFold predicate on the "vehiclePlateNo" field.
func VehiclePlateNoContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldVehiclePlateNo, v))
}

// VehicleTeamNameEQ applies the EQ predicate on the "vehicleTeamName" field.
func VehicleTeamNameEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldVehicleTeamName, v))
}

// VehicleTeamNameNEQ applies the NEQ predicate on the "vehicleTeamName" field.
func VehicleTeamNameNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldVehicleTeamName, v))
}

// VehicleTeamNameIn applies the In predicate on the "vehicleTeamName" field.
func VehicleTeamNameIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldVehicleTeamName, vs...))
}

// VehicleTeamNameNotIn applies the NotIn predicate on the "vehicleTeamName" field.
func VehicleTeamNameNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldVehicleTeamName, vs...))
}

// VehicleTeamNameGT applies the GT predicate on the "vehicleTeamName" field.
func VehicleTeamNameGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldVehicleTeamName, v))
}

// VehicleTeamNameGTE applies the GTE predicate on the "vehicleTeamName" field.
func VehicleTeamNameGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldVehicleTeamName, v))
}

// VehicleTeamNameLT applies the LT predicate on the "vehicleTeamName" field.
func VehicleTeamNameLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldVehicleTeamName, v))
}

// VehicleTeamNameLTE applies the LTE predicate on the "vehicleTeamName" field.
func VehicleTeamNameLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldVehicleTeamName, v))
}

// VehicleTeamNameContains applies the Contains predicate on the "vehicleTeamName" field.
func VehicleTeamNameContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldVehicleTeamName, v))
}

// VehicleTeamNameHasPrefix applies the HasPrefix predicate on the "vehicleTeamName" field.
func VehicleTeamNameHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldVehicleTeamName, v))
}

// VehicleTeamNameHasSuffix applies the HasSuffix predicate on the "vehicleTeamName" field.
func VehicleTeamNameHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldVehicleTeamName, v))
}

// VehicleTeamNameEqualFold applies the EqualFold predicate on the "vehicleTeamName" field.
func VehicleTeamNameEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldVehicleTeamName, v))
}

// VehicleTeamNameContainsFold applies the ContainsFold predicate on the "vehicleTeamName" field.
func VehicleTeamNameContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldVehicleTeamName, v))
}

// MaintRequestTypeEQ applies the EQ predicate on the "maintRequestType" field.
func MaintRequestTypeEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldMaintRequestType, v))
}

// MaintRequestTypeNEQ applies the NEQ predicate on the "maintRequestType" field.
func MaintRequestTypeNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldMaintRequestType, v))
}

// MaintRequestTypeIn applies the In predicate on the "maintRequestType" field.
func MaintRequestTypeIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldMaintRequestType, vs...))
}

// MaintRequestTypeNotIn applies the NotIn predicate on the "maintRequestType" field.
func MaintRequestTypeNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldMaintRequestType, vs...))
}

// MaintRequestTypeGT applies the GT predicate on the "maintRequestType" field.
func MaintRequestTypeGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldMaintRequestType, v))
}

// MaintRequestTypeGTE applies the GTE predicate on the "maintRequestType" field.
func MaintRequestTypeGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldMaintRequestType, v))
}

// MaintRequestTypeLT applies the LT predicate on the "maintRequestType" field.
func MaintRequestTypeLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldMaintRequestType, v))
}

// MaintRequestTypeLTE applies the LTE predicate on the "maintRequestType" field.
func MaintRequestTypeLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldMaintRequestType, v))
}

// MaintRequestTypeContains applies the Contains predicate on the "maintRequestType" field.
func MaintRequestTypeContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldMaintRequestType, v))
}

// MaintRequestTypeHasPrefix applies the HasPrefix predicate on the "maintRequestType" field.
func MaintRequestTypeHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldMaintRequestType, v))
}

// MaintRequestTypeHasSuffix applies the HasSuffix predicate on the "maintRequestType" field.
func MaintRequestTypeHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldMaintRequestType, v))
}

// MaintRequestTypeEqualFold applies the EqualFold predicate on the "maintRequestType" field.
func MaintRequestTypeEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldMaintRequestType, v))
}

// MaintRequestTypeContainsFold applies the ContainsFold predicate on the "maintRequestType" field.
func MaintRequestTypeContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldMaintRequestType, v))
}

// DispatchedStationIdEQ applies the EQ predicate on the "dispatchedStationId" field.
func DispatchedStationIdEQ(v int) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldDispatchedStationId, v))
}

// DispatchedStationIdNEQ applies the NEQ predicate on the "dispatchedStationId" field.
func DispatchedStationIdNEQ(v int) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldDispatchedStationId, v))
}

// DispatchedStationIdIn applies the In predicate on the "dispatchedStationId" field.
func DispatchedStationIdIn(vs ...int) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldDispatchedStationId, vs...))
}

// DispatchedStationIdNotIn applies the NotIn predicate on the "dispatchedStationId" field.
func DispatchedStationIdNotIn(vs ...int) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldDispatchedStationId, vs...))
}

// DispatchedStationIdGT applies the GT predicate on the "dispatchedStationId" field.
func DispatchedStationIdGT(v int) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldDispatchedStationId, v))
}

// DispatchedStationIdGTE applies the GTE predicate on the "dispatchedStationId" field.
func DispatchedStationIdGTE(v int) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldDispatchedStationId, v))
}

// DispatchedStationIdLT applies the LT predicate on the "dispatchedStationId" field.
func DispatchedStationIdLT(v int) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldDispatchedStationId, v))
}

// DispatchedStationIdLTE applies the LTE predicate on the "dispatchedStationId" field.
func DispatchedStationIdLTE(v int) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldDispatchedStationId, v))
}

// StationNameEQ applies the EQ predicate on the "stationName" field.
func StationNameEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldStationName, v))
}

// StationNameNEQ applies the NEQ predicate on the "stationName" field.
func StationNameNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldStationName, v))
}

// StationNameIn applies the In predicate on the "stationName" field.
func StationNameIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldStationName, vs...))
}

// StationNameNotIn applies the NotIn predicate on the "stationName" field.
func StationNameNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldStationName, vs...))
}

// StationNameGT applies the GT predicate on the "stationName" field.
func StationNameGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldStationName, v))
}

// StationNameGTE applies the GTE predicate on the "stationName" field.
func StationNameGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldStationName, v))
}

// StationNameLT applies the LT predicate on the "stationName" field.
func StationNameLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldStationName, v))
}

// StationNameLTE applies the LTE predicate on the "stationName" field.
func StationNameLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldStationName, v))
}

// StationNameContains applies the Contains predicate on the "stationName" field.
func StationNameContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldStationName, v))
}

// StationNameHasPrefix applies the HasPrefix predicate on the "stationName" field.
func StationNameHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldStationName, v))
}

// StationNameHasSuffix applies the HasSuffix predicate on the "stationName" field.
func StationNameHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldStationName, v))
}

// StationNameEqualFold applies the EqualFold predicate on the "stationName" field.
func StationNameEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldStationName, v))
}

// StationNameContainsFold applies the ContainsFold predicate on the "stationName" field.
func StationNameContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldStationName, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Order) predicate.Order {
	return predicate.Order(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Order) predicate.Order {
	return predicate.Order(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Order) predicate.Order {
	return predicate.Order(sql.NotPredicates(p))
}
