// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountColumns holds the columns for the "account" table.
	AccountColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Size: 32},
		{Name: "password", Type: field.TypeString, Size: 32},
		{Name: "token", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AccountTable holds the schema information for the "account" table.
	AccountTable = &schema.Table{
		Name:       "account",
		Columns:    AccountColumns,
		PrimaryKey: []*schema.Column{AccountColumns[0]},
	}
	// OrderColumns holds the columns for the "order" table.
	OrderColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "maint_order_no", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "vehicle_plate_no", Type: field.TypeString, Size: 64},
		{Name: "vehicle_team_name", Type: field.TypeString, Size: 64},
		{Name: "maint_request_type", Type: field.TypeString, Size: 64},
		{Name: "dispatched_station_id", Type: field.TypeInt},
		{Name: "station_name", Type: field.TypeString, Size: 128},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// OrderTable holds the schema information for the "order" table.
	OrderTable = &schema.Table{
		Name:       "order",
		Columns:    OrderColumns,
		PrimaryKey: []*schema.Column{OrderColumns[0]},
	}
	// StationColumns holds the columns for the "station" table.
	StationColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "agency_id", Type: field.TypeInt, Unique: true},
		{Name: "agency_name", Type: field.TypeString, Size: 256},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// StationTable holds the schema information for the "station" table.
	StationTable = &schema.Table{
		Name:       "station",
		Columns:    StationColumns,
		PrimaryKey: []*schema.Column{StationColumns[0]},
	}
	// UserColumns holds the columns for the "user" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 16},
		{Name: "phone", Type: field.TypeString, Unique: true, Nullable: true, Size: 16},
		{Name: "email", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "password_hash", Type: field.TypeString, Size: 128},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PENDING", "ACTIVE", "BANNED"}, Default: "PENDING"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UserTable holds the schema information for the "user" table.
	UserTable = &schema.Table{
		Name:       "user",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountTable,
		OrderTable,
		StationTable,
		UserTable,
	}
)

func init() {
	AccountTable.Annotation = &entsql.Annotation{
		Table: "account",
	}
	OrderTable.Annotation = &entsql.Annotation{
		Table: "order",
	}
	StationTable.Annotation = &entsql.Annotation{
		Table: "station",
	}
	UserTable.Annotation = &entsql.Annotation{
		Table: "user",
	}
}
